version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      reviewers:
      - "tremendous-rewards/platform"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      reviewers:
      - "tremendous-rewards/platform"
