name: Check if the Open API has changed
on:
  schedule:
    - cron:  '0 */3 * * *'

jobs:
  check-update:
    if: github.repository == 'tremendous-rewards/tremendous-node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: check-update
        run: ./bin/check-updates

      - id: create-issue
        if: ${{ steps.check-update.outputs.changed == 'true' }}
        uses: JasonEtco/create-an-issue@v2
        with:
          update_existing: false
          filename: .github/needs-update-template.md
