name: Publish package to NPM
on:
  release:
    types: [published]
jobs:
  publish:
    if: github.repository == 'tremendous-rewards/tremendous-node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      # TODO: Remove `--dry-run` when it's ready
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
